# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-testgen" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "8df7899df42a2ceb817da54a9b47acf39c742b368255d92171f6ff1feb14085d"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e0a809e17963929231ca0e211d776562d40bf7cb361ca104bc42aa9174006f1"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ff7781bdd7c132a07c5c71c3ad5d0583cb0d82035bec7074b0861bdf4513fb7"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "87049b5aa552bb990b4a5cc2d95607723fc43882bb334d76351329e743838311"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-testgen"
  desc "go-testgennal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/go-testgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-testgen"

  # No zap stanza required

end
