# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-testgen" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "b4200290594d4694ee2a028da7d87a8c7c2258247e4094e36acaa290c273645b"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d88aaadc2484e439a833ac7aa15b3d23669b5cbd419b26d8761a944f854e5139"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f35e89a5ae52ee67277b0be77cc5d8c0e15163b636d9b1e2e92a1fe9d7fc21ce"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1f3c73595ab740f923493524ce5b5073ea9f6293a921f329206154e74506fdb"
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-testgen"
  desc "go-testgennal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/go-testgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-testgen"

  # No zap stanza required

end
