# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-testgen" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_darwin_amd64.tar.gz"
      sha256 "864c84dd4c0141ed79d4de4d3ecd0484b217100110d910a9532ef0141659f894"
    end
    on_arm do
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_darwin_arm64.tar.gz"
      sha256 "50c721901b95bdaa194fb1f101d8efa245e6dd5c34fd739e72598a37c721f1c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_linux_amd64.tar.gz"
      sha256 "d5c1636eb612d62a1c8062934152227b29ade4c1bada11302078b6751a901d26"
    end
    on_arm do
      url "https://github.com/padiazg/go-testgen/releases/download/v#{version}/go-testgen_#{version}_linux_arm64.tar.gz"
      sha256 "2a6b41a07f9121b42090535a6bda4d09340eb52ff9f3f608aa32efd4f0875689"
    end
  end

  name "go-testgen"
  desc "go-testgennal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/go-testgen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-testgen"

  # No zap stanza required

end
